name: publish

on: [push]

jobs:
  publish-workflow-tracking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to DockerHub
      run: |
        echo $HUB | docker login -u serverboi --password-stdin
        docker build --tag serverboi/workflow-tracking:latest .
        docker push serverboi/workflow-tracking:latest
      env:
        HUB: ${{ secrets.HUB }}